print('Brand name generator')
print('Enter the city where you were born:')
city = input()
print('Enter the name of your first pet:')
pet = input()
print('Your brand name could be ' + city + ' ' + pet)
